### ISSUE TITLE
[Feature Request] Download multiple sprites at once

### ISSUE THREAD

**Issue by leonardoraele** [yeoji/spritesheet-cutter#2]
It would be great if we could select several sprites and download them all at the same time (as a .tar file) instead of one by one.

**Comment by yeoji** [comment]
Hey @leonardoraele, thanks for the feature request :)

I've implemented this, you can select multiple sprites by holding `shift` and a zip file will be downloaded when export is clicked.

**Comment by leonardoraele** [comment]
Working great, thanks!
